name: Build and deploy API to Docker Hub
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    environment: production
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout the code in the action workspace, in this case ubuntu-latest
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Unit tests
        run: mvn -B test --file pom.xml
      - name: Build with Maven
        run: |
          mvn clean
          mvn -B package --file pom.xml
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/authentication-jwt-spring-boot:latest

